# Generated by Django 4.1.3 on 2023-01-25 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='curso',
            name='visualizacoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='category',
            field=models.CharField(choices=[('PRGRAMACAO', 'Programação'), ('DJANGO', 'Django'), ('ingles', 'Ingles'), ('desenho', 'Desenho')], max_length=15),
        ),
    ]
